// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEpwNfxkdBDoO59K6cOgcJ-3HNEC1FATI',
    appId: '1:854388816800:web:ced188d8f98ec827aa82c5',
    messagingSenderId: '854388816800',
    projectId: 'fir-example-23921',
    authDomain: 'fir-example-23921.firebaseapp.com',
    storageBucket: 'fir-example-23921.firebasestorage.app',
    measurementId: 'G-WZY4BLFPZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnyu6k0l64tW6-lWcTBpSBXX4gKhG57Gg',
    appId: '1:854388816800:android:fca3b4aac1b56218aa82c5',
    messagingSenderId: '854388816800',
    projectId: 'fir-example-23921',
    storageBucket: 'fir-example-23921.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArQ1zm7jvDUakvROuu9das48c8LDBKnhA',
    appId: '1:854388816800:ios:7a90e8badce42eaaaa82c5',
    messagingSenderId: '854388816800',
    projectId: 'fir-example-23921',
    storageBucket: 'fir-example-23921.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArQ1zm7jvDUakvROuu9das48c8LDBKnhA',
    appId: '1:854388816800:ios:7a90e8badce42eaaaa82c5',
    messagingSenderId: '854388816800',
    projectId: 'fir-example-23921',
    storageBucket: 'fir-example-23921.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEpwNfxkdBDoO59K6cOgcJ-3HNEC1FATI',
    appId: '1:854388816800:web:08ef50c1da4f5f0caa82c5',
    messagingSenderId: '854388816800',
    projectId: 'fir-example-23921',
    authDomain: 'fir-example-23921.firebaseapp.com',
    storageBucket: 'fir-example-23921.firebasestorage.app',
    measurementId: 'G-TKFG5EKFY0',
  );
}
